services:
    client:
        build: client/.
        ports:
            - "5173:5173"
    server:
        build: server/.
        ports:
            - "8008:8000"

        volumes:
            - /home:/home

volumes:
    home:

