
services:
    client:
        build: client/.
        ports:
            - "80:80"
        env_file: 
            - ./env/client.env 
            - ./env/user_dir.env
        container_name: "client"
        depends_on:
            - server
    server:
        build: express/.
        ports:
            - "8001:8001"
        env_file: 
            - ./env/server.env
            - ./env/user_dir.env
        container_name: "server"
        volumes:
            - /home:/home

volumes:
    home:

