version: "3.8"

services:
    client:
        build: client/.
        ports:
            - "5173:5173"
        networks: 
            - backend 
        environment:
            VITE_HOST: server
        container_name: "client"
        depends_on:
            - server
        extra_hosts:
            - "host.docker.internal:host-gateway"
    server:
        build: express/.
        networks: 
            - backend 
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PORT=8001
            - HOST=server # not used
        container_name: "server"
        volumes:
            - /home:/home
    nginx:
        build: nginx/.
        ports:
            - "80:80"
            - "8008:8008"
        networks:
            - backend
        container_name: "nginx"
        depends_on:
            - server
            - client
        extra_hosts:
            - "host.docker.internal:host-gateway"



volumes:
    home:

networks:
    backend:
