services:
    client:
        build: client/.
        ports:
            - "5173:5173"
        networks: 
            - mynetwork 
    server:
        build: express/.
        ports:
            - "8008:8008"
        networks: 
            - mynetwork
        volumes:
            - /home:/home

volumes:
    home:

networks:
    mynetwork:
