services:
    client:
        build: client/.
        ports:
            - "5173:5173"
        networks: 
            - backend 
        environment:
            - VITE_HOST=192.168.0.147
        extra_hosts:
            - "host.docker.internal:host-gateway"
    server:
        build: express/.
        ports:
            - "8008:8008"
        networks: 
            - backend 
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - HOST=localhost
            - HOST_IP=host.docker.internal
        volumes:
            - /home:/home

volumes:
    home:

networks:
    backend:
