services:
    client:
        build: client/.
        ports:
            - "5173:5173"
    server:
        build: express/.
        ports:
            - "8008:8008"
        network_mode: host
        volumes:
            - /home:/home

volumes:
    home:

